### ISSUE TITLE
can't mute in Studio One

### ISSUE THREAD

**Issue by gtakecha** [talaviram/TICK#13] opened 2023-05-18 08:23 UTC
I sometimes mute the TICK track in many DAWs to temporarily turn off the sound for pure playback.

For some reason, I'm worried that only Studio One has to deactivate the plug-in instead of muting the track. Other MIDI sound sources that are played by VSTi are properly muted by track mute. I don't know the cause.

**Comment by talaviram** [comment] 2023-05-18 08:27
TICK isn't using midi by design (for MIDI you can use pretty much any sampler/instrument).
If that's not the case, steps to reproduce your problem would help evaluating this better.

Thanks!

**Comment by gtakecha** [comment] 2023-05-18 08:53
ah I see. Studio One seems to be designed to mute only the MIDI notes when muting a MIDI track on the tracks list, not the audio output itself. Mute using Studio One's Mixer screen was able to mute the TICK sound.

However, in this case, the tracks list and the mute status of the Mixer screen were not linked. I'm used to Reaper and Ableton, this is a strange specification...

Anyway thanks for the hints and this great helpful metronome.

**Comment by talaviram** [comment] 2023-05-18 09:35
Great thank you for investigating this thoroughly.

I'm closing the issue.

**Closed by talaviram** 2023-05-18 09:35 UTC
